Update main_action.yml

diff --git a/.github/workflows/main_action.yml b/.github/workflows/main_action.yml
--- a/.github/workflows/main_action.yml
+++ b/.github/workflows/main_action.yml
@@ -99,10 +99,14 @@ jobs:
           IAP_TOKEN: ${{ secrets.IAP_TOKEN }}
           PROMOTE: ${{secrets.PROMOTE}}
         run: |
-          if ! python3 ./scripts/promote.py ./artifact.json; then
-            echo -e "\033[0;31mERROR: ***********************************************************************************"
-            echo "ERROR: There was an issue promoting artifact.json to IAP."
-            echo -e "ERROR: ***********************************************************************************\033[0m"
-            exit 1
+          if [ "$PROMOTE" != "False" ]
+          then
+            if ! python3 ./scripts/promote.py ./artifact.json; then
+              echo -e "\033[0;31mERROR: ***********************************************************************************"
+              echo "ERROR: There was an issue promoting artifact.json to IAP."
+              echo -e "ERROR: ***********************************************************************************\033[0m"
+              exit 1
+            fi
+          else
+            echo -e "PROMOTE set to False, skipping promoting to IAP.
           fi
-          echo $PROMOTE
